---
- hosts: localhost 
  become: true
  tasks:
   - name: redis_service_status
     shell: ps axf | grep redis-server | grep -v grep
     register: redis_service_status
     ignore_errors: true
     args:
      warn: false
   - debug:
      var: redis_service_status.stdout.lines
  # starting the service if it is stopped
   - name: starting redis service
     shell: service redis-server restart
     ignore_errors: true
     when: redis_service_status | failed


...
